# Generated by Django 3.1.6 on 2021-03-23 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import librarian.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='book_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', librarian.models.SmallCharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_by', models.ForeignKey(db_column='reserved_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cover_pic', models.ImageField(upload_to=librarian.models.path_and_rename)),
                ('title', librarian.models.SmallCharField(max_length=100)),
                ('shelf_no', models.IntegerField()),
                ('asin_no', librarian.models.SmallCharField(max_length=100)),
                ('author', librarian.models.SmallCharField(max_length=100)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='librarian.book_category')),
                ('reservation_id', models.ForeignKey(blank=True, db_column='reservation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian.reservation')),
            ],
        ),
    ]
