# Generated by Django 3.1.6 on 2021-03-21 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import librarian.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cover_pic', models.ImageField(upload_to=librarian.models.path_and_rename)),
                ('title', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=150)),
                ('shelf_no', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('reserved_by', models.ForeignKey(blank=True, db_column='reserved_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
