# Generated by Django 3.1.6 on 2021-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_visited_book',
            name='book_1_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latest_visited_book',
            name='book_2_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latest_visited_book',
            name='book_3_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latest_visited_book',
            name='book_4_click',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latest_visited_book',
            name='book_5_click',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
