# Generated by Django 3.1.6 on 2021-04-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20210404_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='admin_notes',
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
