# Generated by Django 3.1.6 on 2021-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_auto_20210328_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
